### ISSUE TITLE
Directory contract_filesystem has to be created as root (fresh install on Ubuntu 14.04)

### ISSUE THREAD

**Issue by AronVanAmmers** [codius-deprecated/codius#3]
When running the first contract after a fresh install of Codius on Ubuntu 14.04 (I used the <a href="https://github.com/codius/example-helloworld">"Hello world" contract</a>), the following is shown:

```
aron@aron-VirtualBox:~/Development/node.js/codius-example-helloworld$ codius run
Error: EACCES, permission denied '/usr/lib/node_modules/codius/node_modules/codius-engine/contract_filesystem/'
    at Object.fs.mkdirSync (fs.js:653:18)
    at FileManager.storeFileWithHash (/usr/lib/node_modules/codius/node_modules/codius-engine/lib/filemanager.js:24:8)
    at null.<anonymous> (/usr/lib/node_modules/codius/lib/commands/run.js:25:17)
    at emit (events.js:95:17)
    at /usr/lib/node_modules/codius/node_modules/codius-engine/lib/compiler.js:85:11
    at Array.forEach (native)
    at Compiler.compileModule (/usr/lib/node_modules/codius/node_modules/codius-engine/lib/compiler.js:81:31)
    at RunCommand.run (/usr/lib/node_modules/codius/lib/commands/run.js:28:31)
    at Codius.runCommand (/usr/lib/node_modules/codius/lib/codius.js:41:29)
    at /usr/lib/node_modules/codius/bin/codius-cli.js:23:10
```

As a workaround, I ran this contract once as root so the directory gets created, and set public permissions:

```
sudo codius run
sudo chmod 777 /usr/lib/node_modules/codius/node_modules/codius-engine/contract_filesystem/
```

After this, this and other contracts run fine as non-root users. It would be good to include it as an initial install step of `codius` or `codius-engine` though.

**Comment by AronVanAmmers** [comment]
Reported here as well: https://github.com/codius/example-helloworld/issues/1

**Comment by emschwartz** [comment]
Do you still have this issue?

**Comment by AronVanAmmers** [comment]
Just tested and the issue seems to be solved. Experiencing another one wrt libraries, will create another issue for that.
